// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUimZYtfvkTRFWav6LjSIa1n163-dGfMk',
    appId: '1:1078132301789:web:8621e70bea848d99cda034',
    messagingSenderId: '1078132301789',
    projectId: 'habitflow-c2c79',
    authDomain: 'habitflow-c2c79.firebaseapp.com',
    storageBucket: 'habitflow-c2c79.firebasestorage.app',
    measurementId: 'G-SLZ5DTE8B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qCZ05UrtFm6wPt7dlkzkETAD6GN_MqY',
    appId: '1:1078132301789:android:f4018115c2e055f4cda034',
    messagingSenderId: '1078132301789',
    projectId: 'habitflow-c2c79',
    storageBucket: 'habitflow-c2c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-6tcw-u2XuxuYbreg_8Q7Qdi3C_wXVQ',
    appId: '1:1078132301789:ios:b11c46ef74337f70cda034',
    messagingSenderId: '1078132301789',
    projectId: 'habitflow-c2c79',
    storageBucket: 'habitflow-c2c79.firebasestorage.app',
    iosBundleId: 'com.example.habitflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO-6tcw-u2XuxuYbreg_8Q7Qdi3C_wXVQ',
    appId: '1:1078132301789:ios:b11c46ef74337f70cda034',
    messagingSenderId: '1078132301789',
    projectId: 'habitflow-c2c79',
    storageBucket: 'habitflow-c2c79.firebasestorage.app',
    iosBundleId: 'com.example.habitflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUimZYtfvkTRFWav6LjSIa1n163-dGfMk',
    appId: '1:1078132301789:web:64677f4c68ed962ccda034',
    messagingSenderId: '1078132301789',
    projectId: 'habitflow-c2c79',
    authDomain: 'habitflow-c2c79.firebaseapp.com',
    storageBucket: 'habitflow-c2c79.firebasestorage.app',
    measurementId: 'G-PGF36CSSH4',
  );
}